//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCon_General.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iCon_General.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        public static string Btn_Add {
            get {
                return ResourceManager.GetString("Btn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply ähnelt.
        /// </summary>
        public static string Btn_Apply {
            get {
                return ResourceManager.GetString("Btn_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string Btn_Cancel {
            get {
                return ResourceManager.GetString("Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change ähnelt.
        /// </summary>
        public static string Btn_Change {
            get {
                return ResourceManager.GetString("Btn_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear ähnelt.
        /// </summary>
        public static string Btn_Clear {
            get {
                return ResourceManager.GetString("Btn_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Submit Jobs ähnelt.
        /// </summary>
        public static string Btn_Submit {
            get {
                return ResourceManager.GetString("Btn_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _File ähnelt.
        /// </summary>
        public static string MainMenu_File {
            get {
                return ResourceManager.GetString("MainMenu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Load ähnelt.
        /// </summary>
        public static string MainMenu_File_Load {
            get {
                return ResourceManager.GetString("MainMenu_File_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load _Folder ähnelt.
        /// </summary>
        public static string MainMenu_File_LoadFolder {
            get {
                return ResourceManager.GetString("MainMenu_File_LoadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _New ähnelt.
        /// </summary>
        public static string MainMenu_File_New {
            get {
                return ResourceManager.GetString("MainMenu_File_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Save ähnelt.
        /// </summary>
        public static string MainMenu_File_Save {
            get {
                return ResourceManager.GetString("MainMenu_File_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save _As ähnelt.
        /// </summary>
        public static string MainMenu_File_SaveAs {
            get {
                return ResourceManager.GetString("MainMenu_File_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Help ähnelt.
        /// </summary>
        public static string MainMenu_Help {
            get {
                return ResourceManager.GetString("MainMenu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Info ähnelt.
        /// </summary>
        public static string MainMenu_Help_Info {
            get {
                return ResourceManager.GetString("MainMenu_Help_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _View ähnelt.
        /// </summary>
        public static string MainMenu_View {
            get {
                return ResourceManager.GetString("MainMenu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Status Window ähnelt.
        /// </summary>
        public static string MainMenu_View_StatusWindow {
            get {
                return ResourceManager.GetString("MainMenu_View_StatusWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _3D Viewer ähnelt.
        /// </summary>
        public static string MainMenu_View_Tab3D {
            get {
                return ResourceManager.GetString("MainMenu_View_Tab3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Extended Settings ähnelt.
        /// </summary>
        public static string MainMenu_View_TabExtSettings {
            get {
                return ResourceManager.GetString("MainMenu_View_TabExtSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Project File ähnelt.
        /// </summary>
        public static string MainMenu_View_TabProjFile {
            get {
                return ResourceManager.GetString("MainMenu_View_TabProjFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die iCon - Kinetic Monte-Carlo Simulation of Ionic Conductivity (BETA Version) ähnelt.
        /// </summary>
        public static string MainWindow_BaseTitle {
            get {
                return ResourceManager.GetString("MainWindow_BaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string ProgressWindow_CancelBtn {
            get {
                return ResourceManager.GetString("ProgressWindow_CancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description: ähnelt.
        /// </summary>
        public static string ProgressWindow_Description {
            get {
                return ResourceManager.GetString("ProgressWindow_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Progress: ähnelt.
        /// </summary>
        public static string ProgressWindow_Progress {
            get {
                return ResourceManager.GetString("ProgressWindow_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status: ähnelt.
        /// </summary>
        public static string ProgressWindow_Status {
            get {
                return ResourceManager.GetString("ProgressWindow_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Task Progress ähnelt.
        /// </summary>
        public static string ProgressWindow_Title {
            get {
                return ResourceManager.GetString("ProgressWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 3D Viewer ähnelt.
        /// </summary>
        public static string TabHeader_3D {
            get {
                return ResourceManager.GetString("TabHeader_3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Energies ähnelt.
        /// </summary>
        public static string TabHeader_Energies {
            get {
                return ResourceManager.GetString("TabHeader_Energies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extended Settings ähnelt.
        /// </summary>
        public static string TabHeader_ExtSettings {
            get {
                return ResourceManager.GetString("TabHeader_ExtSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Job Description ähnelt.
        /// </summary>
        public static string TabHeader_JobDef {
            get {
                return ResourceManager.GetString("TabHeader_JobDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Job Settings ähnelt.
        /// </summary>
        public static string TabHeader_JobSettings {
            get {
                return ResourceManager.GetString("TabHeader_JobSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Jumps ähnelt.
        /// </summary>
        public static string TabHeader_Jumps {
            get {
                return ResourceManager.GetString("TabHeader_Jumps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project File ähnelt.
        /// </summary>
        public static string TabHeader_ProjFile {
            get {
                return ResourceManager.GetString("TabHeader_ProjFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Structure ähnelt.
        /// </summary>
        public static string TabHeader_Structure {
            get {
                return ResourceManager.GetString("TabHeader_Structure", resourceCulture);
            }
        }
    }
}
